export const LEVELS = [
  {
    id: 1,
    name: 'L1: 単一感染源',
    width: 8,
    height: 8,
    nanos: [[3, 3]],
    walls: [[1, 1], [1, 2], [6, 6]],
    goals: [],
    tools: { block: 6, purge: 2, splitter: 1 },
    rules: { diagonalGrowth: false, purgeCooldown: 2 },
    win: { surviveTurns: 7, eradicateAll: false, protectGoalTurns: 0 },
    lose: { maxNanoRatio: 0.6, maxTurns: 10, stuckLose: false },
  },
  {
    id: 2,
    name: 'L2: 回廊封鎖',
    width: 10,
    height: 8,
    nanos: [[1, 4], [8, 2]],
    walls: [[4, 0], [4, 1], [4, 2], [4, 5], [4, 6], [4, 7]],
    goals: [],
    tools: { block: 7, purge: 2, splitter: 2 },
    rules: { diagonalGrowth: false, purgeCooldown: 2 },
    win: { surviveTurns: 8, eradicateAll: false, protectGoalTurns: 0 },
    lose: { maxNanoRatio: 0.58, maxTurns: 11, stuckLose: false },
  },
  {
    id: 3,
    name: 'L3: 交差点分断',
    width: 10,
    height: 10,
    nanos: [[2, 2], [7, 7]],
    walls: [[5, 0], [5, 1], [5, 2], [5, 7], [5, 8], [5, 9], [0, 5], [1, 5], [8, 5], [9, 5]],
    goals: [],
    tools: { block: 6, purge: 3, splitter: 2 },
    rules: { diagonalGrowth: false, purgeCooldown: 2 },
    win: { surviveTurns: 9, eradicateAll: false, protectGoalTurns: 0 },
    lose: { maxNanoRatio: 0.57, maxTurns: 12, stuckLose: false },
  },
  {
    id: 4,
    name: 'L4: コア防衛入門',
    width: 12,
    height: 10,
    nanos: [[1, 1], [10, 8]],
    walls: [[5, 3], [6, 3], [5, 4], [6, 4], [5, 5], [6, 5]],
    goals: [[6, 8]],
    tools: { block: 8, purge: 2, splitter: 2 },
    rules: { diagonalGrowth: false, purgeCooldown: 2 },
    win: { surviveTurns: 0, eradicateAll: false, protectGoalTurns: 8 },
    lose: { maxNanoRatio: 0.6, maxTurns: 12, stuckLose: false },
  },
  {
    id: 5,
    name: 'L5: 3感染源',
    width: 12,
    height: 12,
    nanos: [[1, 6], [6, 1], [10, 10]],
    walls: [[3, 3], [4, 3], [5, 3], [8, 8], [8, 9], [8, 10], [2, 9], [3, 9], [4, 9]],
    goals: [[11, 0]],
    tools: { block: 9, purge: 3, splitter: 2 },
    rules: { diagonalGrowth: false, purgeCooldown: 2 },
    win: { surviveTurns: 0, eradicateAll: false, protectGoalTurns: 9 },
    lose: { maxNanoRatio: 0.6, maxTurns: 13, stuckLose: false },
  },
  {
    id: 6,
    name: 'L6: 侵食全滅',
    width: 12,
    height: 12,
    nanos: [[2, 2], [9, 9], [2, 9]],
    walls: [[6, 4], [6, 5], [6, 6], [6, 7]],
    goals: [],
    tools: { block: 7, purge: 4, splitter: 3 },
    rules: { diagonalGrowth: false, purgeCooldown: 1 },
    win: { surviveTurns: 0, eradicateAll: true, protectGoalTurns: 0 },
    lose: { maxNanoRatio: 0.56, maxTurns: 14, stuckLose: false },
  },
  {
    id: 7,
    name: 'L7: 斜め増殖解禁',
    width: 14,
    height: 12,
    nanos: [[1, 1], [12, 1], [6, 10]],
    walls: [[5, 2], [5, 3], [5, 4], [8, 7], [9, 7], [10, 7], [3, 8], [3, 9]],
    goals: [[7, 5]],
    tools: { block: 10, purge: 3, splitter: 3 },
    rules: { diagonalGrowth: true, purgeCooldown: 2 },
    win: { surviveTurns: 0, eradicateAll: false, protectGoalTurns: 10 },
    lose: { maxNanoRatio: 0.5, maxTurns: 14, stuckLose: false },
  },
  {
    id: 8,
    name: 'L8: 分断必須',
    width: 14,
    height: 14,
    nanos: [[2, 2], [11, 2], [2, 11], [11, 11]],
    walls: [[6, 0], [6, 1], [6, 2], [7, 11], [7, 12], [7, 13], [0, 6], [1, 6], [2, 6], [11, 7], [12, 7], [13, 7]],
    goals: [[7, 7]],
    tools: { block: 9, purge: 3, splitter: 4 },
    rules: { diagonalGrowth: true, purgeCooldown: 2 },
    win: { surviveTurns: 0, eradicateAll: false, protectGoalTurns: 10 },
    lose: { maxNanoRatio: 0.48, maxTurns: 15, stuckLose: false },
  },
  {
    id: 9,
    name: 'L9: 総力戦',
    width: 16,
    height: 14,
    nanos: [[1, 1], [8, 1], [14, 3], [2, 12], [13, 12]],
    walls: [[5, 5], [6, 5], [7, 5], [8, 5], [9, 5], [10, 5], [6, 8], [7, 8], [8, 8], [9, 8]],
    goals: [[8, 7]],
    tools: { block: 10, purge: 4, splitter: 4 },
    rules: { diagonalGrowth: true, purgeCooldown: 1 },
    win: { surviveTurns: 11, eradicateAll: false, protectGoalTurns: 0 },
    lose: { maxNanoRatio: 0.46, maxTurns: 16, stuckLose: false },
  },
  {
    id: 10,
    name: 'L10: 終局コア防衛',
    width: 20,
    height: 16,
    nanos: [[1, 1], [10, 1], [18, 2], [3, 14], [10, 14], [18, 14]],
    walls: [[9, 6], [10, 6], [11, 6], [9, 7], [11, 7], [9, 8], [10, 8], [11, 8], [4, 4], [5, 4], [14, 11], [15, 11]],
    goals: [[10, 7]],
    tools: { block: 12, purge: 4, splitter: 5 },
    rules: { diagonalGrowth: true, purgeCooldown: 1 },
    win: { surviveTurns: 0, eradicateAll: false, protectGoalTurns: 12 },
    lose: { maxNanoRatio: 0.45, maxTurns: 18, stuckLose: false },
  },
];
